# Generated by Django 5.1 on 2024-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_sessionvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulativerewardpool',
            name='totals',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchantvolume',
            name='totals',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sessionvolume',
            name='totals',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='totalvolume',
            name='totals',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
