# Generated by Django 5.1 on 2024-09-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='is_increase',
            field=models.BooleanField(default=True, help_text='Indicates if this is an increase (True) or decrease (False).'),
        ),
    ]
