services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    shm_size: 1gb
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "max_connections=200"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: ["/entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://django_user:django_password@db:5432/django_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery:
    build: .
    command: celery -A interface worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://django_user:django_password@db:5432/django_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A interface beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://django_user:django_password@db:5432/django_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

#  flower:
#    build: .
#    command: ["flower", "--port=5555", "--broker=redis://redis:6379/0"]
#    ports:
#      - "5555:5555"
#    depends_on:
#      - redis
#    environment:
#      DATABASE_URL: postgres://django_user:django_password@db:5432/django_db
