services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    shm_size: 1gb
    ports:
      - "${DATABASE_PORT}:5432"
    command: ["postgres", "-c", "max_connections=200"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
#    command: ["/entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    command: ["/entrypoint.sh", "uvicorn", "interface.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DEBUG_PRO: ${DEBUG_PRO}
      DEBUG_TEST: ${DEBUG_TEST}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
#      CORS_ALLOWED_ORIGINS: "http://localhost:5173,https://d9-test-server.q6z4kzhr.uk"

  celery:
    build: .
    command: celery -A interface worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DEBUG_PRO: ${DEBUG_PRO}
      DEBUG_TEST: ${DEBUG_TEST}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A interface beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DEBUG_PRO: ${DEBUG_PRO}
      DEBUG_TEST: ${DEBUG_TEST}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

#  flower:
#    build: .
#    command: ["flower", "--port=5555", "--broker=redis://redis:6379/0"]
#    ports:
#      - "5555:5555"
#    depends_on:
#      - redis
#    environment:
#      DATABASE_URL: postgres://django_user:django_password@db:5432/django_db
