# Generated by Django 5.1 on 2024-09-17 18:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('d9', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('usdt', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('params', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('token', models.CharField(choices=[('d9', 'D9'), ('usdt', 'USDT')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('is_increase', models.BooleanField(default=True, help_text='Indicates if this is an increase (True) or decrease (False).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
