# Generated by Django 5.1 on 2024-09-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='d9',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usdt',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
    ]
