# Generated by Django 5.1 on 2024-09-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_d9_alter_wallet_usdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='d9',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24),
        ),
    ]
