# Generated by Django 5.0.7 on 2024-07-27 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMarketInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('d9_token', models.IntegerField()),
                ('usdt_token', models.IntegerField()),
                ('d9_rate', models.FloatField()),
                ('usdt_rate', models.FloatField()),
            ],
        ),
    ]
