# Generated by Django 5.0.7 on 2024-07-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmarketinformation',
            name='d9_token',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tokenmarketinformation',
            name='usdt_token',
            field=models.BigIntegerField(),
        ),
    ]
