# Generated by Django 5.0.7 on 2024-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0002_alter_tokenmarketinformation_d9_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmarketinformation',
            name='d9_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenmarketinformation',
            name='usdt_token',
            field=models.CharField(max_length=255),
        ),
    ]
