# Generated by Django 5.0.7 on 2024-08-24 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0003_alter_tokenmarketinformation_d9_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityProvider',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('d9_token', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_token', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
