# Generated by Django 5.1 on 2024-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0004_liquidityprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidityprovider',
            name='d9_token',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='liquidityprovider',
            name='provider',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='liquidityprovider',
            name='usdt_token',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenmarketinformation',
            name='d9_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tokenmarketinformation',
            name='d9_token',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenmarketinformation',
            name='usdt_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tokenmarketinformation',
            name='usdt_token',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
