# Generated by Django 5.1 on 2024-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyprofile',
            name='name',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currencyprofile',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
