# Generated by Django 5.1 on 2024-09-09 08:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('extrinsic_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('total_fee_amount', models.CharField(max_length=255, unique=True)),
                ('block_number', models.IntegerField(db_index=True)),
                ('form_address', models.CharField(db_index=True, max_length=255, unique=True)),
                ('to_address', models.CharField(db_index=True, max_length=255, unique=True)),
                ('usdt', models.CharField(blank=True, default='0', max_length=255, unique=True)),
                ('d9', models.CharField(blank=True, default='0', max_length=255, unique=True)),
                ('point', models.CharField(blank=True, default='0', max_length=255, unique=True)),
                ('actions', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
