# Generated by Django 5.1 on 2024-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='订单ID')),
                ('operation', models.CharField(max_length=100, verbose_name='交易类型')),
                ('params', models.JSONField(verbose_name='交易参数')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='交易状态')),
                ('balance_check', models.JSONField(blank=True, null=True, verbose_name='余额查询结果')),
                ('transaction_result', models.JSONField(blank=True, null=True, verbose_name='交易执行结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
