# Generated by Django 5.1 on 2024-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='balance_check',
        ),
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.FloatField(default=0, verbose_name='手续费'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_address',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_address',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
