# Generated by Django 5.0.7 on 2024-08-05 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantExpiry',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expiry_date', models.CharField(default='1567958400', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='USDTBalances',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('balance_usdt', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalances',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('balance_d9', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBurningProfile',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount_burned', models.CharField(max_length=255)),
                ('balance_due', models.CharField(max_length=255)),
                ('balance_paid', models.CharField(max_length=255)),
                ('last_withdrawal', models.CharField(max_length=255)),
                ('last_burn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserMerchantProfile',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('green_points', models.CharField(max_length=255)),
                ('relationship_green_points', models.CharField(max_length=255)),
                ('relationship_red_points', models.CharField(max_length=255)),
                ('last_conversion', models.CharField(max_length=255)),
                ('redeemed_usdt', models.CharField(max_length=255)),
                ('redeemed_d9', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserToNodeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=255)),
                ('node_name', models.CharField(max_length=255)),
                ('vote', models.CharField(max_length=255)),
            ],
        ),
    ]
