# Generated by Django 5.1 on 2024-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userburningprofile',
            name='amount_burned',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userburningprofile',
            name='balance_due',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userburningprofile',
            name='balance_paid',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userburningprofile',
            name='last_burn',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userburningprofile',
            name='last_withdrawal',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermerchantprofile',
            name='relationship_green_points',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermerchantprofile',
            name='relationship_red_points',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
