# Generated by Django 5.0.7 on 2024-07-31 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0003_userburningprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantExpiry',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expiry_date', models.CharField(default='1567958400', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
