# Generated by Django 5.0.7 on 2024-07-31 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0004_merchantexpiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMerchantProfile',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('green_points', models.CharField(max_length=255)),
                ('relationship_factors', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('red_points', models.CharField(max_length=255)),
                ('last_conversion', models.IntegerField()),
                ('redeemed_usdt', models.CharField(max_length=255)),
                ('redeemed_d9', models.CharField(max_length=255)),
                ('created_at', models.IntegerField()),
            ],
        ),
    ]
