# Generated by Django 5.0.7 on 2024-07-31 10:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0005_usermerchantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermerchantprofile',
            name='relationship_factors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
