# Generated by Django 5.0.7 on 2024-07-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0006_alter_usermerchantprofile_relationship_factors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermerchantprofile',
            name='relationship_factors',
        ),
    ]
