# Generated by Django 5.0.7 on 2024-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0007_remove_usermerchantprofile_relationship_factors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermerchantprofile',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usermerchantprofile',
            name='last_conversion',
            field=models.CharField(max_length=255),
        ),
    ]
